source "https://rubygems.org"

gem "base64"
gem "csv"
gem "bigdecimal"
gem "jekyll", "~> 4.4"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "webrick"
gem "minimal-mistakes-jekyll"
gem "jekyll-include-cache"
