source "https://rubygems.org"

gem "base64"
gem "csv"
gem "bigdecimal"
gem "jekyll", "~> 4.4"
gem "jekyll-sass-converter", "~> 3.0.0"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-remote-theme"
gem "webrick"
gem "jekyll-include-cache"
